// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFolder(arg1:string):Promise<void>;

export function OpenInFileManager(arg1:string):Promise<void>;
